name: Connexion GitHub -> Alwaysdata

on: [push]

jobs:
  Connexion:
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du dépôt
        uses: actions/checkout@v4

      - name: Vérifier la clé privée
        run: |
          echo "${{ secrets.SSH_KEY }}" | base64 --decode > id_rsa
          chmod 600 id_rsa
          ls -l id_rsa
          cat id_rsa | head -n 5  # Vérifie bien que la clé est écrite

      - name: Connexion SSH avec le serveur Alwaysdata
        run: |
          ssh -i id_rsa -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@ssh-${{ secrets.USERNAME }}.alwaysdata.net "echo 'Connexion réussie depuis GitHub Actions !'"
